spring.application.name=user-microservices
server.port=8083
server.address=0.0.0.0
eureka.instance.instance-id=${spring.application.name}:${random.uuid}
eureka.instance.prefer-ip-address=true

# DEFAULZONE ES SOLO PARA DOCKER EN LOCAL SE DEBE COMENTAR
eureka.client.service-url.defaultZone=http://services:8761/eureka

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=esthetic_base

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

mail.username=gs.vera92@gmail.com
mail.password=hdhgoefspbmhaogi
mail.port=587
mail.host=smtp.gmail.com

#url.front=http://localhost:3000
#url.localhost=http://localhost:8002
url.hostname=https://meredith-aesthetic.com

## para debugear luego se debe quitar para prod
#logging.level.org.springframework.security=DEBUG
# ESTO SOLO ES PARA DOCKER
my.property.api.gateway=http://api-gateway:8002
env.exponotificationurl=https://exp.host/--/api/v2/push/send

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB

# SPACE DIGITAL OCEAN
cloud.aws.s3.endpoint=https://meredith-aesthetic-pictures.sfo3.digitaloceanspaces.com
cloud.aws.se.bucket=meredith-aesthetic-pictures
cloud.aws.s3.dirprofile=profile
cloud.aws.s3.dirinfocompany=infocompany
cloud.aws.s3.region=sfo3